config/routes.rb
Nantsocial::Application.routes.draw do
  resources :members

  resources :ramblings

  devise_for :users
  root 'ramblings#index'
  get 'about' => 'pages#about'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/rambling.rb
class Rambling < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, :styles => { :large => "800x800", :medium => "450x450>", :thumb => "150x150>" }, :default_url => "http://uk.virginmoneygiving.com/fundraiser-web/img/branding/no-profile-image.png"

	validates :image, presence: false
  validates :description, presence: false
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ramblings

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render action: 'show', status: :created, location: @member }
      else
        format.html { render action: 'new' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/ramblings_controller.rb
class RamblingsController < ApplicationController
  before_action :set_rambling, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @ramblings = Rambling.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 25)
  end

  def show
  end

  def new
    @rambling = current_user.ramblings.build
  end

  def edit
  end

  def create
    @rambling = current_user.ramblings.build(rambling_params)
      if @rambling.save
        redirect_to @rambling, notice: 'Success! You rambled.'
      else
        render action: 'new'
      end
  end

  def update
      if @rambling.update(rambling_params)
        redirect_to @rambling, notice: 'Yay! Successfully updated.'
      else
        render action: 'edit'
      end
  end

  def destroy
    @rambling.destroy
      redirect_to ramblings_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rambling
      @rambling = Rambling.find(params[:id])
    end

    def correct_user
      @rambling = current_user.ramblings.find_by(id: params[:id])
      redirect_to ramblings_path, notice: "Grumpy cats disapproves of you unauthorized edits to other's rambling" if @rambling.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rambling_params
      params.require(:rambling).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ramblings_helper.rb
module RamblingsHelper
end

app/views/layouts/_ffffooter.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
  <div class="container">
    <small>Made with <span class="glyphicon glyphicon-heart-empty"></span> in Panama City Beach</small>
  </div>
</nav>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-fixed-bottom" role="navigation">
  <div class="container">
    <small>Made with <span class="glyphicon glyphicon-heart-empty"></span> in Panama City Beach</small>
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "NANTSOCIAL", root_path, class: "navbar-brand"%>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to root_path do%>
          <span class="glyphicon glyphicon-home"></span> HOME<% end %>
        </li>
      <% if user_signed_in? %>
        <li><%= link_to new_rambling_path do%>
          <span class="glyphicon glyphicon-plus"></span> NEW POST<% end %>
        </li>
        <% end %>
      <li><%= link_to about_path do%>
          <span class="glyphicon glyphicon-info-sign"></span> ABOUT<% end %>
        </li>
      <% if user_signed_in? %>
      <li><%= link_to edit_user_registration_path do%>
          <span class="glyphicon glyphicon-cog"></span> SETTINGS<% end %>
        </li>
        <li><%= link_to destroy_user_session_path, method: :delete do%>
          <span class="glyphicon glyphicon-cog"></span> LOG OUT<% end %>
        </li>
      <% else %>
        <li><%= link_to "LOG IN", new_user_session_path %></li>
        <li><%= link_to "SIGN UP", new_user_registration_path %></li>
       <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nantsocial</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
    <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.description %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @member.description %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/pages/_home.html.erb
<div class="jumbotron center">
     <h1>Welcome to Nantsocial</h1>
     <% if user_signed_in? %>
          #do something
     <% else %>
       <p>
         <%= link_to "LOG IN", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "SIGN UP", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>  
</div>

app/views/pages/about.html.erb
<h1>About NantSocial</h1>
<p>Details go here...</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
     <h1>Welcome to Nantsocial</h1>
     <% if user_signed_in? %>
          # do something
     <% else %>
       <p>
         <%= link_to "LOG IN", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "SIGN UP", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>  
</div>

app/views/ramblings/_form.html.erb
<%= form_for @rambling, html: { multipart: true } do |f| %>
  <% if @rambling.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rambling.errors.count, "error") %> prohibited this rambling from being saved:</h2>

      <ul>
      <% @rambling.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :"Attach an Image" %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Post", class: "btn btn-danger" %>
  </div>
<% end %>

app/views/ramblings/edit.html.erb
<h1>Editing rambling</h1>

<%= render 'form' %>

<%= link_to 'Show', @rambling %> |
<%= link_to 'Back', ramblings_path %>

app/views/ramblings/index.html.erb
<%= render 'pages/home' if user_signed_in? %>

<div id="ramblings" class="transitions-enabled">
  <% @ramblings.each do |rambling| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(rambling.image.url(:medium)), rambling %>
      <div class="panel-body">
      <%= rambling.description %><br />
      <strong><%= rambling.user.name if rambling.user %></strong>
      <% if rambling.user == current_user %>
        <div class="actions">
          <%= link_to edit_rambling_path(rambling) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to rambling, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
        </div>
      <% end %>
    </div>
    </div>
  <% end %>
</div>
<div class="center">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/ramblings/new.html.erb
<h1>Post Something!</h1>
<%= render 'form' %>

<%= link_to 'Back', ramblings_path %>

app/views/ramblings/show.html.erb
<%= link_to 'Back', ramblings_path, class: "btn btn-primary btn-large" %>
<div class="row">
  <div class="col-md-offset-1 col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @rambling.image.url(:large) %>
      </div>
      <div class="panel-body">
        <p><h3><%= @rambling.description %></h3></p>
        <p><strong><%= @rambling.user.name if @rambling.user %></strong></p>

        <% if @rambling.user == current_user %>
         <%= link_to edit_rambling_path(@rambling) do %>
        <span class="glyphicon glyphicon-edit"></span>
        Edit
      <% end %>
        <% end %>

      </div>
    </div>
  </div>
</div>